# print("Hello World!")
# print("Hello Again!")
# print("I like typing this!")
# print("This is fun.")
# print("Yay! Printing stuff!")
# print("I'd rather you 'not'.")
print('I "said" do not touch this.')
